/**
 * MagMark 2.0 - Xiaohongshu Zipper
 * Creates carousel ZIP packages for Xiaohongshu
 */

import * as archiver from 'archiver';
import { Readable } from 'stream';

export interface XiaohongshuOptions {
  /** Image format */
  format?: 'jpg' | 'png';
  /** Image quality (for JPEG) */
  quality?: number;
  /** Resolution mode */
  resolution?: 'quick' | 'standard' | 'print';
  /** Primary or alternative dimensions */
  sizeVariant?: 'primary' | 'alternative';
  /** Add page numbers */
  addPageNumbers?: boolean;
  /** Cover image index */
  coverIndex?: number;
}

const PLATFORM_SPECS = {
  primary: {
    width: 1080,
    height: 1440,
    ratio: '3:4',
    description: 'Standard Xiaohongshu post',
  },
  alternative: {
    width: 1242,
    height: 1660,
    ratio: '3:4',
    description: 'Higher resolution alternative',
  },
};

const RESOLUTION_MULTIPLIERS = {
  quick: 2,      // 2160 x 2880
  standard: 3,   // 3240 x 4320 (300dpi equivalent)
  print: 6,      // 6480 x 8640 (600dpi equivalent)
};

/**
 * Get dimensions for specified variant and resolution
 */
export function getDimensions(
  variant: 'primary' | 'alternative' = 'primary',
  resolution: 'quick' | 'standard' | 'print' = 'standard'
): { width: number; height: number; ratio: string } {
  const spec = PLATFORM_SPECS[variant];
  const multiplier = RESOLUTION_MULTIPLIERS[resolution];
  
  return {
    width: spec.width * multiplier,
    height: spec.height * multiplier,
    ratio: spec.ratio,
  };
}

/**
 * Generate filenames for carousel images
 */
export function generateFilenames(
  count: number,
  options: { prefix?: string; format?: string } = {}
): string[] {
  const { prefix = 'xiaohongshu', format = 'jpg' } = options;
  
  return Array.from({ length: count }, (_, i) => {
    const pageNum = String(i + 1).padStart(2, '0');
    return `${prefix}_${pageNum}.${format}`;
  });
}

/**
 * Create carousel ZIP package
 */
export async function createCarouselZip(
  imageBuffers: Buffer[],
  options: XiaohongshuOptions = {}
): Promise<Buffer> {
  const {
    format = 'jpg',
    addPageNumbers = false,
    sizeVariant = 'primary',
    resolution = 'standard',
  } = options;
  
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', {
      zlib: { level: 9 },
    });
    
    const chunks: Buffer[] = [];
    
    archive.on('data', (chunk) => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);
    
    // Add metadata file
    const dimensions = getDimensions(sizeVariant, resolution);
    const metadata = {
      platform: 'xiaohongshu',
      type: 'carousel',
      specs: {
        ...dimensions,
        format,
        pages: imageBuffers.length,
      },
      createdAt: new Date().toISOString(),
    };
    
    archive.append(JSON.stringify(metadata, null, 2), {
      name: 'metadata.json',
    });
    
    // Add README
    const readme = generateReadme(imageBuffers.length, dimensions);
    archive.append(readme, { name: 'README.txt' });
    
    // Add images
    const filenames = generateFilenames(imageBuffers.length, { format });
    
    imageBuffers.forEach((buffer, i) => {
      archive.append(buffer, { name: filenames[i] });
    });
    
    archive.finalize();
  });
}

/**
 * Generate README content
 */
function generateReadme(
  pageCount: number,
  dimensions: { width: number; height: number; ratio: string }
): string {
  return `
MagMark 2.0 - Xiaohongshu Carousel Package
==========================================

Specifications:
- Platform: Xiaohongshu (小红书)
- Format: Carousel / 图文
- Dimensions: ${dimensions.width} x ${dimensions.height}px
- Aspect Ratio: ${dimensions.ratio}
- Pages: ${pageCount}

Upload Instructions:
1. Open Xiaohongshu app
2. Tap the "+" button to create new post
3. Select all ${pageCount} images from this folder
4. Arrange in order if needed
5. Add title, description, and tags
6. Publish!

Tips:
- First image will be the cover
- Recommended to add text overlay on cover
- Use relevant hashtags for better reach
- Optimal posting time: 12:00-13:00 or 20:00-22:00

Generated by MagMark 2.0
https://github.com/magmark/magmark-2.0
`.trim();
}

/**
 * Validate image dimensions
 */
export function validateDimensions(
  width: number,
  height: number,
  tolerance: number = 0.01
): { valid: boolean; ratio: number; expectedRatio: number } {
  const ratio = width / height;
  const expectedRatio = 3 / 4; // Xiaohongshu standard
  
  const valid = Math.abs(ratio - expectedRatio) <= tolerance;
  
  return { valid, ratio, expectedRatio };
}

/**
 * Generate preview grid HTML
 */
export function generatePreviewGrid(
  imageBuffers: Buffer[],
  options: { columns?: number; gap?: number } = {}
): string {
  const { columns = 3, gap = 10 } = options;
  
  const images = imageBuffers.map((buffer, i) => {
    const base64 = buffer.toString('base64');
    return `
      <div class="preview-item" data-index="${i}">
        <img src="data:image/jpeg;base64,${base64}" alt="Page ${i + 1}" />
        <span class="page-number">${i + 1}</span>
      </div>
    `;
  });
  
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, sans-serif;
      background: #f5f5f5;
      padding: 20px;
    }
    .preview-grid {
      display: grid;
      grid-template-columns: repeat(${columns}, 1fr);
      gap: ${gap}px;
      max-width: 1200px;
      margin: 0 auto;
    }
    .preview-item {
      position: relative;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .preview-item img {
      width: 100%;
      height: auto;
      display: block;
    }
    .page-number {
      position: absolute;
      top: 8px;
      left: 8px;
      background: rgba(0,0,0,0.7);
      color: white;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
    }
    h1 {
      text-align: center;
      margin-bottom: 20px;
      color: #333;
    }
  </style>
</head>
<body>
  <h1>Xiaohongshu Carousel Preview</h1>
  <div class="preview-grid">
    ${images.join('')}
  </div>
</body>
</html>
  `.trim();
}

/**
 * Estimate file size
 */
export function estimateFileSize(
  pageCount: number,
  options: { format?: string; quality?: number; resolution?: string } = {}
): string {
  const { format = 'jpg', quality = 85, resolution = 'standard' } = options;
  
  const dimensions = getDimensions('primary', resolution as any);
  const pixels = dimensions.width * dimensions.height;
  
  // Rough estimation
  const bytesPerPixel = format === 'png' ? 4 : quality / 100 * 0.5;
  const totalBytes = pixels * bytesPerPixel * pageCount;
  
  if (totalBytes > 1024 * 1024 * 1024) {
    return `${(totalBytes / 1024 / 1024 / 1024).toFixed(2)} GB`;
  } else if (totalBytes > 1024 * 1024) {
    return `${(totalBytes / 1024 / 1024).toFixed(2)} MB`;
  } else {
    return `${(totalBytes / 1024).toFixed(2)} KB`;
  }
}

export default {
  getDimensions,
  generateFilenames,
  createCarouselZip,
  validateDimensions,
  generatePreviewGrid,
  estimateFileSize,
};
