/**
 * MagMark — WeChat (公众号) Theme System
 * 
 * 将"微信公众号排版助手"的主题系统集成到 MagMark。
 * 每个主题使用内联 CSS 样式字符串，以便复制后可直接在微信后台展示。
 */

export interface WechatThemeStyles {
  container?: string;
  h1: string;
  h2: string;
  h3: string;
  p: string;
  blockquote: string;
  code: string;
  pre: string;
  strong: string;
  em: string;
  ul: string;
  ol: string;
  li: string;
  hr: string;
  img: string;
  table: string;
  thead: string;
  tbody: string;
  th: string;
  td: string;
  a: string;
}

export interface WechatTheme {
  name: string;
  nameEn: string;
  accent: string;
  isDark?: boolean;
  styles: WechatThemeStyles;
}

const BASE_P = 'font-size: 16px; line-height: 1.85; margin: 20px 0; text-align: justify; text-justify: inter-ideograph; letter-spacing: 0.02em;';
const BASE_CODE = 'padding: 3px 6px; border-radius: 4px; font-family: "Fira Code", "Courier New", monospace; font-size: 14px;';
const BASE_PRE = 'padding: 16px; border-radius: 8px; overflow-x: auto; margin: 20px 0; font-family: "Fira Code", "Courier New", monospace; font-size: 14px; line-height: 1.6;';
const BASE_IMG = 'max-width: 100%; height: auto; border-radius: 8px; margin: 20px auto; display: block;';
const BASE_TABLE = 'width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 15px;';
const BASE_TH = 'padding: 10px 14px; text-align: left; font-weight: 600;';
const BASE_TD = 'padding: 9px 14px; border-bottom: 1px solid rgba(0,0,0,0.08);;';

export const WECHAT_THEMES: Record<string, WechatTheme> = {
  minimalist: {
    name: '极简主义',
    nameEn: 'Minimalist',
    accent: '#333333',
    styles: {
      container: 'background-color: #ffffff; color: #3e3e3e; padding: 20px;',
      h1: 'font-size: 24px; font-weight: bold; margin: 30px 0 20px; text-align: center; color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; line-height: 1.4;',
      h2: 'font-size: 20px; font-weight: bold; margin: 25px 0 15px; color: #333; border-left: 4px solid #333; padding-left: 10px; line-height: 1.4;',
      h3: 'font-size: 18px; font-weight: bold; margin: 20px 0 10px; color: #555; line-height: 1.4;',
      p: BASE_P + ' color: #3e3e3e;',
      blockquote: 'margin: 20px 0; padding: 15px 20px; background: #f9f9f9; border-left: 4px solid #ddd; color: #666; font-style: italic;',
      code: BASE_CODE + ' background: #f4f4f4; color: #e83e8c;',
      pre: BASE_PRE + ' background: #f4f4f4; color: #3e3e3e; border: 1px solid #eee;',
      strong: 'font-weight: bold; color: #000;',
      em: 'font-style: italic;',
      ul: 'margin: 15px 0; padding-left: 25px; list-style-type: disc;',
      ol: 'margin: 15px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 8px 0; line-height: 1.6; font-size: 16px; color: #3e3e3e;',
      hr: 'border: none; border-top: 1px solid #eee; margin: 30px 0;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #f4f4f4;',
      tbody: '',
      th: BASE_TH + ' color: #333; border-bottom: 2px solid #ddd;',
      td: BASE_TD + ' color: #3e3e3e;',
      a: 'color: #333; text-decoration: underline;',
    }
  },
  elegant: {
    name: '优雅青绿',
    nameEn: 'Elegant Teal',
    accent: '#00a7a7',
    styles: {
      container: 'background-color: #ffffff; color: #444444; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #00a7a7; letter-spacing: 2px; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #fff; background: #00a7a7; padding: 8px 15px; border-radius: 4px; display: block; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #00a7a7; border-bottom: 1px dashed #00a7a7; padding-bottom: 5px; line-height: 1.4;',
      p: BASE_P + ' color: #444;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #f0fafa; border-radius: 8px; border-left: 6px solid #00a7a7; color: #007a7a;',
      code: BASE_CODE + ' background: #e6f7f7; color: #008080;',
      pre: BASE_PRE + ' background: #e6f7f7; color: #008080;',
      strong: 'font-weight: bold; color: #00a7a7;',
      em: 'font-style: italic; color: #00a7a7;',
      ul: 'margin: 18px 0; padding-left: 25px; list-style-type: circle;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #444;',
      hr: 'border: none; border-top: 2px dotted #00a7a7; margin: 40px 0; opacity: 0.3;',
      img: BASE_IMG + ' border: 2px solid #e6f7f7;',
      table: BASE_TABLE,
      thead: 'background: #00a7a7;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #444; border-bottom-color: #e6f7f7;',
      a: 'color: #00a7a7; text-decoration: underline;',
    }
  },
  modern: {
    name: '活力橙红',
    nameEn: 'Modern Orange',
    accent: '#ff5722',
    styles: {
      container: 'background-color: #fffaf9; color: #2c3e50; padding: 20px;',
      h1: 'font-size: 28px; font-weight: 900; margin: 40px 0 30px; text-align: center; color: #ff5722; line-height: 1.3;',
      h2: 'font-size: 24px; font-weight: bold; margin: 35px 0 25px; color: #333; border-bottom: 4px solid #ff5722; padding-bottom: 5px; line-height: 1.3;',
      h3: 'font-size: 20px; font-weight: bold; margin: 30px 0 20px; color: #ff5722; line-height: 1.3;',
      p: BASE_P + ' color: #2c3e50;',
      blockquote: 'margin: 30px 0; padding: 25px; background: #fff5f2; border-radius: 12px; border: 1px solid #ffccbc; color: #d84315;',
      code: BASE_CODE + ' background: #ffe0b2; color: #e65100;',
      pre: BASE_PRE + ' background: #fff5f2; color: #d84315; border: 1px solid #ffccbc;',
      strong: 'font-weight: 800; color: #ff5722;',
      em: 'font-style: italic; text-decoration: underline; text-decoration-color: #ffccbc;',
      ul: 'margin: 20px 0; padding-left: 25px; list-style-type: square;',
      ol: 'margin: 20px 0; padding-left: 25px; list-style-type: decimal-leading-zero;',
      li: 'margin: 12px 0; line-height: 1.8; font-size: 16px; color: #2c3e50;',
      hr: 'height: 4px; background: linear-gradient(to right, #ff5722, transparent); border: none; margin: 50px 0;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #ff5722;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #2c3e50; border-bottom-color: #ffccbc;',
      a: 'color: #ff5722; text-decoration: underline;',
    }
  },
  business: {
    name: '商务深蓝',
    nameEn: 'Business Blue',
    accent: '#1a237e',
    styles: {
      container: 'background-color: #ffffff; color: #333333; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #1a237e; border-top: 3px solid #1a237e; border-bottom: 3px solid #1a237e; padding: 10px 0; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #1a237e; border-left: 6px solid #1a237e; padding-left: 15px; background: #e8eaf6; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #3949ab; line-height: 1.4;',
      p: BASE_P + ' color: #333;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #f5f5f5; border-left: 5px solid #1a237e; color: #555;',
      code: BASE_CODE + ' background: #e8eaf6; color: #1a237e;',
      pre: BASE_PRE + ' background: #e8eaf6; color: #1a237e;',
      strong: 'font-weight: bold; color: #1a237e;',
      em: 'font-style: italic;',
      ul: 'margin: 18px 0; padding-left: 25px; list-style-type: disc;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #333;',
      hr: 'border: none; border-top: 1px solid #1a237e; margin: 40px 0; opacity: 0.2;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #1a237e;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #333;',
      a: 'color: #1a237e; text-decoration: underline;',
    }
  },
  retro: {
    name: '复古纸张',
    nameEn: 'Retro Paper',
    accent: '#8d6e63',
    styles: {
      container: 'background-color: #fdf6e3; color: #4e342e; padding: 20px;',
      h1: 'font-size: 25px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #5d4037; font-family: serif; line-height: 1.4;',
      h2: 'font-size: 21px; font-weight: bold; margin: 30px 0 20px; color: #5d4037; text-align: center; padding-bottom: 10px; line-height: 1.4;',
      h3: 'font-size: 18px; font-weight: bold; margin: 25px 0 15px; color: #795548; font-family: serif; line-height: 1.4;',
      p: BASE_P + ' color: #4e342e;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #efebe9; border: 1px dashed #8d6e63; color: #5d4037; font-style: italic;',
      code: BASE_CODE + ' background: #d7ccc8; color: #3e2723;',
      pre: BASE_PRE + ' background: #efebe9; color: #4e342e; border: 1px dashed #8d6e63;',
      strong: 'font-weight: bold; color: #3e2723;',
      em: 'font-style: italic;',
      ul: 'margin: 18px 0; padding-left: 25px; list-style-type: circle;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: lower-roman;',
      li: 'margin: 12px 0; line-height: 1.8; font-size: 16px; color: #4e342e;',
      hr: 'border: none; border-top: 1px dashed #8d6e63; margin: 40px 0;',
      img: BASE_IMG + ' filter: sepia(20%);',
      table: BASE_TABLE,
      thead: 'background: #d7ccc8;',
      tbody: '',
      th: BASE_TH + ' color: #5d4037; border-bottom: 2px solid #8d6e63;',
      td: BASE_TD + ' color: #4e342e; border-bottom-color: #d7ccc8;',
      a: 'color: #8d6e63; text-decoration: underline;',
    }
  },
  pink: {
    name: '少女粉色',
    nameEn: 'Girly Pink',
    accent: '#ec407a',
    styles: {
      container: 'background-color: #fff9fb; color: #555555; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #ec407a; text-shadow: 2px 2px 0px #fce4ec; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #fff; background: #f06292; padding: 8px 20px; border-radius: 20px; display: block; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #ec407a; border-left: 4px solid #f8bbd0; padding-left: 10px; line-height: 1.4;',
      p: BASE_P + ' color: #555;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #fff1f5; border-radius: 15px; border: 1px solid #f8bbd0; color: #ad1457;',
      code: BASE_CODE + ' background: #fce4ec; color: #c2185b;',
      pre: BASE_PRE + ' background: #fff1f5; color: #ad1457; border: 1px solid #f8bbd0;',
      strong: 'font-weight: bold; color: #ec407a;',
      em: 'font-style: italic; color: #f06292;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #555;',
      hr: 'border: none; border-top: 2px solid #f8bbd0; margin: 40px 0;',
      img: BASE_IMG + ' border: 2px solid #f8bbd0;',
      table: BASE_TABLE,
      thead: 'background: #f06292;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #555; border-bottom-color: #f8bbd0;',
      a: 'color: #ec407a; text-decoration: underline;',
    }
  },
  dark: {
    name: '极简暗黑',
    nameEn: 'Dark Minimal',
    accent: '#ffffff',
    isDark: true,
    styles: {
      container: 'background-color: #000000; color: #ffffff; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #ffffff; background: #111111; padding: 15px 0; border-radius: 4px; line-height: 1.4; border: 1px solid #333;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #ffffff; border-left: 4px solid #ffffff; padding-left: 15px; line-height: 1.4; background: #050505;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #ffffff; border-bottom: 1px solid #333; padding-bottom: 5px; line-height: 1.4;',
      p: BASE_P + ' color: #f0f0f0;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #0a0a0a; border-left: 4px solid #ffffff; color: #d1d1d1; font-style: italic;',
      code: BASE_CODE + ' background: #1a1a1a; color: #ff79c6; border: 1px solid #333;',
      pre: BASE_PRE + ' background: #0a0a0a; color: #f0f0f0; border: 1px solid #333;',
      strong: 'font-weight: bold; color: #ffffff; text-decoration: underline; text-decoration-color: #444;',
      em: 'font-style: italic; color: #dddddd;',
      ul: 'margin: 18px 0; padding-left: 25px; list-style-type: disc; color: #f0f0f0;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal; color: #f0f0f0;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #f0f0f0;',
      hr: 'border: none; border-top: 1px solid #444; margin: 40px 0;',
      img: BASE_IMG + ' border: 1px solid #333;',
      table: BASE_TABLE,
      thead: 'background: #1a1a1a;',
      tbody: '',
      th: BASE_TH + ' color: #ffffff; border-bottom: 1px solid #444;',
      td: BASE_TD + ' color: #f0f0f0; border-bottom-color: #333;',
      a: 'color: #ffffff; text-decoration: underline; text-decoration-style: dotted;',
    }
  },
  forest: {
    name: '森林呼吸',
    nameEn: 'Forest Breath',
    accent: '#2e7d32',
    styles: {
      container: 'background-color: #f1f8e9; color: #333; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #1b5e20; border-bottom: 2px solid #a5d6a7; padding-bottom: 10px; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #2e7d32; border-left: 5px solid #2e7d32; padding-left: 12px; background: #f1f8e9; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #388e3c; line-height: 1.4;',
      p: BASE_P + ' color: #333;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #f9fbe7; border-left: 4px solid #c0ca33; color: #558b2f;',
      code: BASE_CODE + ' background: #f1f8e9; color: #2e7d32;',
      pre: BASE_PRE + ' background: #f9fbe7; color: #2e7d32; border: 1px solid #c5e1a5;',
      strong: 'font-weight: bold; color: #1b5e20;',
      em: 'font-style: italic; color: #43a047;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #333;',
      hr: 'border: none; border-top: 1px solid #a5d6a7; margin: 40px 0;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #2e7d32;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #333; border-bottom-color: #c5e1a5;',
      a: 'color: #2e7d32; text-decoration: underline;',
    }
  },
  ocean: {
    name: '深海之蓝',
    nameEn: 'Deep Ocean',
    accent: '#0277bd',
    styles: {
      container: 'background-color: #e1f5fe; color: #37474f; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #01579b; padding: 10px 0; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #0277bd; border-bottom: 2px solid #0277bd; display: block; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #0288d1; line-height: 1.4;',
      p: BASE_P + ' color: #37474f;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #e1f5fe; border-radius: 0 20px 20px 0; border-left: 5px solid #0277bd; color: #01579b;',
      code: BASE_CODE + ' background: #e1f5fe; color: #0277bd;',
      pre: BASE_PRE + ' background: #e1f5fe; color: #0277bd; border: 1px solid #b3e5fc;',
      strong: 'font-weight: bold; color: #01579b;',
      em: 'font-style: italic; color: #039be5;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #37474f;',
      hr: 'border: none; border-top: 1px solid #b3e5fc; margin: 40px 0;',
      img: BASE_IMG + ' border: 2px solid #b3e5fc;',
      table: BASE_TABLE,
      thead: 'background: #0277bd;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #37474f; border-bottom-color: #b3e5fc;',
      a: 'color: #0277bd; text-decoration: underline;',
    }
  },
  lavender: {
    name: '薰衣草紫',
    nameEn: 'Lavender',
    accent: '#7e57c2',
    styles: {
      container: 'background-color: #f3e5f5; color: #424242; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #512da8; border-bottom: 2px dashed #d1c4e9; padding-bottom: 10px; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #7e57c2; border-left: 5px solid #b39ddb; padding-left: 12px; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #9575cd; line-height: 1.4;',
      p: BASE_P + ' color: #424242;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #f3e5f5; border-radius: 10px; color: #6a1b9a; border: 1px solid #e1bee7;',
      code: BASE_CODE + ' background: #f3e5f5; color: #7e57c2;',
      pre: BASE_PRE + ' background: #f3e5f5; color: #7e57c2; border: 1px solid #e1bee7;',
      strong: 'font-weight: bold; color: #4527a0;',
      em: 'font-style: italic; color: #7e57c2;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #424242;',
      hr: 'border: none; border-top: 1px solid #d1c4e9; margin: 40px 0;',
      img: BASE_IMG + ' border: 2px solid #e1bee7;',
      table: BASE_TABLE,
      thead: 'background: #7e57c2;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #424242; border-bottom-color: #d1c4e9;',
      a: 'color: #7e57c2; text-decoration: underline;',
    }
  },
  coffee: {
    name: '咖啡时光',
    nameEn: 'Coffee Time',
    accent: '#6d4c41',
    styles: {
      container: 'background-color: #fdfdfd; color: #4e342e; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #3e2723; border-bottom: 2px solid #d7ccc8; padding-bottom: 10px; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #fff; background: #6d4c41; padding: 8px 15px; border-radius: 4px; display: block; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #5d4037; border-left: 4px solid #d7ccc8; padding-left: 10px; line-height: 1.4;',
      p: BASE_P + ' color: #4e342e; font-family: "PingFang SC", "Microsoft YaHei", sans-serif;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #efebe9; border-radius: 8px; color: #5d4037;',
      code: BASE_CODE + ' background: #d7ccc8; color: #3e2723;',
      pre: BASE_PRE + ' background: #efebe9; color: #4e342e;',
      strong: 'font-weight: bold; color: #3e2723;',
      em: 'font-style: italic;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #4e342e;',
      hr: 'border: none; border-top: 1px solid #d7ccc8; margin: 40px 0;',
      img: BASE_IMG + ' border: 2px solid #d7ccc8;',
      table: BASE_TABLE,
      thead: 'background: #6d4c41;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #4e342e; border-bottom-color: #d7ccc8;',
      a: 'color: #6d4c41; text-decoration: underline;',
    }
  },
  cyberpunk: {
    name: '赛博朋克',
    nameEn: 'Cyberpunk',
    accent: '#ff00ff',
    isDark: true,
    styles: {
      container: 'background-color: #000000; color: #00ff00; padding: 20px;',
      h1: 'font-size: 28px; font-weight: 900; margin: 40px 0 30px; text-align: center; color: #fff; text-shadow: 0 0 10px #ff00ff, 0 0 20px #ff00ff; border: 2px solid #ff00ff; padding: 15px; line-height: 1.3;',
      h2: 'font-size: 24px; font-weight: bold; margin: 35px 0 25px; color: #00ffff; text-shadow: 0 0 5px #00ffff; border-left: 8px solid #ff00ff; padding-left: 15px; line-height: 1.3;',
      h3: 'font-size: 20px; font-weight: bold; margin: 30px 0 20px; color: #ffff00; text-shadow: 0 0 5px #ffff00; line-height: 1.3;',
      p: BASE_P + ' color: #00ff00; font-family: "Courier New", monospace; letter-spacing: 0.05em;',
      blockquote: 'margin: 30px 0; padding: 25px; background: rgba(255, 0, 255, 0.05); border: 2px solid #ff00ff; color: #ffffff;',
      code: BASE_CODE + ' background: #0a0a0a; border: 1px solid #00ffff; color: #00ffff;',
      pre: BASE_PRE + ' background: #0a0a0a; color: #00ff00; border: 1px solid #00ffff;',
      strong: 'font-weight: bold; color: #ff00ff; text-shadow: 0 0 5px #ff00ff;',
      em: 'font-style: italic; color: #00ffff;',
      ul: 'margin: 20px 0; padding-left: 25px; color: #00ff00;',
      ol: 'margin: 20px 0; padding-left: 25px; list-style-type: decimal; color: #00ff00;',
      li: 'margin: 12px 0; line-height: 1.8; font-size: 16px; color: #00ff00;',
      hr: 'height: 2px; background: linear-gradient(to right, #ff00ff, #00ffff, #ffff00); border: none; margin: 50px 0;',
      img: BASE_IMG + ' border: 2px solid #ff00ff; filter: saturate(1.5);',
      table: BASE_TABLE,
      thead: 'background: #ff00ff;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #00ff00; border-bottom-color: #333;',
      a: 'color: #00ffff; text-decoration: underline; text-shadow: 0 0 3px #00ffff;',
    }
  },
  premium_gold: {
    name: '尊享金典',
    nameEn: 'Premium Gold',
    accent: '#bf953f',
    styles: {
      container: 'background-color: #fdfbf0; color: #333; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 40px 0 30px; text-align: center; color: #bf953f; border: 2px solid #bf953f; padding: 15px; background: #fdfbf0; box-shadow: 4px 4px 0px #bf953f; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 35px 0 25px; color: #bf953f; border-bottom: 2px solid #bf953f; padding-bottom: 5px; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 30px 0 20px; color: #8a6d3b; border-left: 5px solid #bf953f; padding-left: 12px; line-height: 1.4;',
      p: BASE_P + ' color: #333;',
      blockquote: 'margin: 30px 0; padding: 25px; background: #fcf8e3; border: 1px solid #faebcc; border-radius: 4px; color: #8a6d3b; font-style: italic; border-left: 8px solid #bf953f;',
      code: BASE_CODE + ' background: #fdfbf0; border: 1px solid #bf953f; color: #8a6d3b;',
      pre: BASE_PRE + ' background: #fdfbf0; color: #8a6d3b; border: 1px solid #bf953f;',
      strong: 'font-weight: bold; color: #bf953f;',
      em: 'font-style: italic; color: #8a6d3b;',
      ul: 'margin: 20px 0; padding-left: 25px;',
      ol: 'margin: 20px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 12px 0; line-height: 1.8; font-size: 16px; color: #333;',
      hr: 'border: none; height: 1px; background: linear-gradient(to right, transparent, #bf953f, transparent); margin: 50px 0;',
      img: BASE_IMG + ' border: 2px solid #bf953f;',
      table: BASE_TABLE,
      thead: 'background: #bf953f;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #333; border-bottom-color: #faebcc;',
      a: 'color: #bf953f; text-decoration: underline;',
    }
  },
  tech_blueprint: {
    name: '技术蓝图',
    nameEn: 'Tech Blueprint',
    accent: '#0052cc',
    styles: {
      container: 'background-color: #ffffff; color: #172b4d; padding: 20px;',
      h1: 'font-size: 28px; font-weight: bold; margin: 45px 0 35px; text-align: left; color: #0052cc; border-left: 10px solid #0052cc; padding-left: 20px; background: #f4f5f7; line-height: 1.4;',
      h2: 'font-size: 24px; font-weight: bold; margin: 40px 0 30px; color: #172b4d; border-bottom: 2px solid #0052cc; padding-bottom: 8px; line-height: 1.4;',
      h3: 'font-size: 20px; font-weight: bold; margin: 35px 0 25px; color: #0052cc; background: #deebff; padding: 5px 15px; border-radius: 4px; line-height: 1.4;',
      p: BASE_P + ' color: #172b4d;',
      blockquote: 'margin: 35px 0; padding: 25px; background: #ebf5ff; border-radius: 8px; border: 1px solid #cce5ff; color: #004085;',
      code: BASE_CODE + ' background: #f4f5f7; color: #0052cc; border: 1px solid #dfe1e6;',
      pre: BASE_PRE + ' background: #f4f5f7; color: #0052cc; border: 1px solid #dfe1e6;',
      strong: 'font-weight: bold; color: #0052cc;',
      em: 'font-style: italic; color: #6b778c;',
      ul: 'margin: 22px 0; padding-left: 30px; list-style-type: circle;',
      ol: 'margin: 22px 0; padding-left: 30px; list-style-type: decimal;',
      li: 'margin: 15px 0; line-height: 1.7; font-size: 16px; color: #172b4d;',
      hr: 'border: none; border-top: 2px dashed #dfe1e6; margin: 60px 0;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #0052cc;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #172b4d; border-bottom-color: #dfe1e6;',
      a: 'color: #0052cc; text-decoration: underline;',
    }
  },
  sunset: {
    name: '落日余晖',
    nameEn: 'Sunset Glow',
    accent: '#ef6c00',
    styles: {
      container: 'background-color: #fff3e0; color: #4e342e; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #e65100; text-shadow: 1px 1px 2px #ffe0b2; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #fff; background: linear-gradient(45deg, #f4511e, #ffb300); padding: 8px 20px; border-radius: 5px; display: block; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #ef6c00; line-height: 1.4;',
      p: BASE_P + ' color: #4e342e;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #fff3e0; border-left: 5px solid #ff9800; color: #e65100;',
      code: BASE_CODE + ' background: #ffe0b2; color: #e65100;',
      pre: BASE_PRE + ' background: #fff3e0; color: #e65100; border: 1px solid #ffcc80;',
      strong: 'font-weight: bold; color: #bf360c;',
      em: 'font-style: italic; color: #f4511e;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #4e342e;',
      hr: 'border: none; border-top: 1px solid #ffcc80; margin: 40px 0;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #ef6c00;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #4e342e; border-bottom-color: #ffcc80;',
      a: 'color: #ef6c00; text-decoration: underline;',
    }
  },
  mint: {
    name: '薄荷清爽',
    nameEn: 'Mint Fresh',
    accent: '#4db6ac',
    styles: {
      container: 'background-color: #e0f2f1; color: #333; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #00796b; border-bottom: 2px solid #b2dfdb; padding-bottom: 10px; line-height: 1.4;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #fff; background: #4db6ac; padding: 8px 15px; border-radius: 4px; display: block; line-height: 1.4;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #00796b; border-left: 4px solid #b2dfdb; padding-left: 10px; line-height: 1.4;',
      p: BASE_P + ' color: #333;',
      blockquote: 'margin: 25px 0; padding: 20px; background: #e0f2f1; border-radius: 8px; color: #004d40;',
      code: BASE_CODE + ' background: #b2dfdb; color: #00796b;',
      pre: BASE_PRE + ' background: #e0f2f1; color: #00796b; border: 1px solid #b2dfdb;',
      strong: 'font-weight: bold; color: #004d40;',
      em: 'font-style: italic;',
      ul: 'margin: 18px 0; padding-left: 25px;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.7; font-size: 16px; color: #333;',
      hr: 'border: none; border-top: 1px solid #b2dfdb; margin: 40px 0;',
      img: BASE_IMG + ' border: 2px solid #b2dfdb;',
      table: BASE_TABLE,
      thead: 'background: #4db6ac;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #333; border-bottom-color: #b2dfdb;',
      a: 'color: #4db6ac; text-decoration: underline;',
    }
  },
  hand_written: {
    name: '手写文艺',
    nameEn: 'Handwritten',
    accent: '#5c6bc0',
    styles: {
      container: 'background-color: #fafafa; color: #3d3d3d; padding: 20px;',
      h1: 'font-size: 26px; font-weight: bold; margin: 35px 0 25px; text-align: center; color: #3949ab; border-bottom: 3px double #c5cae9; padding-bottom: 15px; line-height: 1.5;',
      h2: 'font-size: 22px; font-weight: bold; margin: 30px 0 20px; color: #3949ab; position: relative; padding-bottom: 8px; line-height: 1.5;',
      h3: 'font-size: 19px; font-weight: bold; margin: 25px 0 15px; color: #5c6bc0; line-height: 1.5;',
      p: BASE_P + ' color: #3d3d3d; line-height: 2;',
      blockquote: 'margin: 25px 0; padding: 20px 25px; background: #f8f8ff; border-left: 4px solid #9fa8da; color: #4a4a6a; font-style: italic;',
      code: BASE_CODE + ' background: #e8eaf6; color: #3949ab;',
      pre: BASE_PRE + ' background: #f3f4fb; color: #3949ab; border: 1px solid #c5cae9;',
      strong: 'font-weight: bold; color: #3949ab;',
      em: 'font-style: italic; color: #7986cb; text-decoration: underline; text-decoration-style: wavy; text-decoration-color: #c5cae9;',
      ul: 'margin: 18px 0; padding-left: 25px; list-style-type: disc;',
      ol: 'margin: 18px 0; padding-left: 25px; list-style-type: decimal;',
      li: 'margin: 10px 0; line-height: 1.9; font-size: 16px; color: #3d3d3d;',
      hr: 'border: none; border-top: 2px dashed #c5cae9; margin: 40px 0;',
      img: BASE_IMG + ' border: 2px solid #e8eaf6;',
      table: BASE_TABLE,
      thead: 'background: #5c6bc0;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #3d3d3d; border-bottom-color: #c5cae9;',
      a: 'color: #5c6bc0; text-decoration: underline; text-decoration-style: wavy;',
    }
  },
  wechat_green: {
    name: '微信绿 (官方)',
    nameEn: 'WeChat Green',
    accent: '#07c160',
    styles: {
      container: 'background-color: #ffffff; color: #333333; padding: 20px;',
      h1: 'font-size: 22px; font-weight: bold; margin: 28px 0 18px; color: #07c160; text-align: center; border-bottom: 2px solid #07c160; padding-bottom: 8px; line-height: 1.4;',
      h2: 'font-size: 19px; font-weight: bold; margin: 24px 0 14px; color: #06ae56; border-left: 4px solid #07c160; padding-left: 10px; line-height: 1.4;',
      h3: 'font-size: 17px; font-weight: bold; margin: 20px 0 10px; color: #06ae56; line-height: 1.4;',
      p: BASE_P + ' color: #333333; font-size: 15px;',
      blockquote: 'margin: 20px 0; padding: 14px 18px; background: #f0faf4; border-left: 4px solid #07c160; color: #067a40; font-size: 15px;',
      code: BASE_CODE + ' background: #f0faf4; color: #06ae56; font-size: 13px;',
      pre: BASE_PRE + ' background: #f0faf4; color: #06ae56; border: 1px solid #c8e6d0;',
      strong: 'font-weight: bold; color: #07c160;',
      em: 'font-style: italic;',
      ul: 'margin: 15px 0; padding-left: 22px; list-style-type: disc;',
      ol: 'margin: 15px 0; padding-left: 22px; list-style-type: decimal;',
      li: 'margin: 8px 0; line-height: 1.7; font-size: 15px; color: #333333;',
      hr: 'border: none; border-top: 1px solid #e0e0e0; margin: 28px 0;',
      img: BASE_IMG,
      table: BASE_TABLE,
      thead: 'background: #07c160;',
      tbody: '',
      th: BASE_TH + ' color: #fff; border-bottom: none;',
      td: BASE_TD + ' color: #333333; border-bottom-color: #e0e0e0;',
      a: 'color: #07c160; text-decoration: underline;',
    }
  },
};

export const WECHAT_FONT_OPTIONS = [
  { name: '系统默认', value: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif' },
  { name: '思源黑体', value: '"Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif' },
  { name: '思源宋体', value: '"Noto Serif SC", "Source Han Serif SC", Georgia, serif' },
  { name: '楷体', value: 'STKaiti, "楷体", "KaiTi", Georgia, serif' },
  { name: '微软雅黑', value: '"Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", sans-serif' },
  { name: '苹方', value: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif' },
];

export const WECHAT_DEVICE_OPTIONS = {
  iphone: { name: 'iPhone 15 Pro', width: 375, label: '手机 (375px)' },
  android: { name: 'Android (Pixel)', width: 412, label: '安卓 (412px)' },
  tablet: { name: 'iPad Air', width: 768, label: '平板 (768px)' },
  desktop: { name: '桌面宽屏', width: 800, label: '宽屏 (800px)' },
};
