/** Scoped editing chrome; never included in exported cover artwork. */
const icons: Record<string,string> = {
 move:'<path d="M12 3v18M3 12h18M9 6l3-3 3 3M6 9l-3 3 3 3M9 18l3 3 3-3M18 9l3 3-3 3"/>',
 text:'<path d="M4 5h16M12 5v15M8 20h8M4 5v3M20 5v3"/>',
 image:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="1.5"/><path d="m21 15-5-5-6 7-3-3-4 5"/>',
 guides:'<rect x="4" y="4" width="16" height="16" rx="1"/><path d="M8 2v20M16 2v20M2 8h20M2 16h20"/>',
 eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 hidden:'<path d="m3 3 18 18M10.6 5.1A11 11 0 0 1 22 12a16 16 0 0 1-3.1 3.8M6.4 6.4A19 19 0 0 0 2 12s3.5 7 10 7a12 12 0 0 0 5-1.1M10 10a3 3 0 0 0 4 4"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
 unlock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 7.5-2"/>',
 up:'<path d="m6 14 6-6 6 6"/>',down:'<path d="m6 10 6 6 6-6"/>',
 reset:'<path d="M3 10a9 9 0 1 1 1 8M3 4v6h6"/>',
};
export const icon = (name:string) => `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]??''}</svg>`;
export const workspaceHTML = `<style>
#mm-responsive-cover{--rc-line:#44464a;--rc-muted:#b1b3b9;box-sizing:border-box;inset:0;margin:auto;width:min(1380px,98vw);max-width:98vw;height:min(920px,96dvh);max-height:96dvh;padding:0;border:1px solid #55585e;border-radius:12px;background:#242527;color:#eeeef1;font:13px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Noto Sans CJK SC',sans-serif;box-shadow:0 24px 80px #0006;overflow:hidden}
#mm-responsive-cover[open]{display:flex;flex-direction:column}#mm-responsive-cover::backdrop{background:#131416a8}#mm-responsive-cover *{box-sizing:border-box}#mm-responsive-cover [hidden]{display:none!important}
#mm-responsive-cover button,#mm-responsive-cover select,#mm-responsive-cover input,#mm-responsive-cover textarea{font:inherit;color:inherit;border:1px solid var(--rc-line);border-radius:5px;background:#242527;padding:6px 8px;min-height:30px}
#mm-responsive-cover button{cursor:pointer}#mm-responsive-cover button:hover:not(:disabled){background:#494c52}#mm-responsive-cover button:disabled,#mm-responsive-cover input:disabled,#mm-responsive-cover textarea:disabled,#mm-responsive-cover select:disabled{opacity:.4;cursor:not-allowed}#mm-responsive-cover :focus-visible{outline:2px solid #80b5ff;outline-offset:2px}
#mm-responsive-cover header{height:56px;display:flex;align-items:center;gap:12px;padding:0 18px;border-bottom:1px solid #17181a;background:#303135;flex-shrink:0}#mm-responsive-cover header h2{font-size:15px;letter-spacing:.04em;margin:0;font-weight:600}#mm-responsive-cover header span{font-size:11px;color:var(--rc-muted)}#mm-responsive-cover header button:first-of-type{margin-left:auto}
#mm-responsive-cover .rc-body{display:grid;grid-template-columns:44px minmax(0,1fr) 302px;min-height:0;flex:1;overflow:hidden}#mm-responsive-cover .rc-rail{padding:10px 4px;display:flex;flex-direction:column;gap:8px;background:#303135;border-right:1px solid #17181a}#mm-responsive-cover .rc-rail button{width:34px;height:36px;padding:7px;border-color:transparent}#mm-responsive-cover .rc-rail button[aria-pressed=true]{background:#414c60;border-color:#80b5ff}#mm-responsive-cover .rc-rail hr{width:22px;border:0;border-top:1px solid var(--rc-line);margin:4px auto}
#mm-responsive-cover .rc-stage{display:flex;flex-direction:column;min-width:0;min-height:0;padding:0;overflow:auto}#mm-responsive-cover .rc-options{padding:10px 16px;display:flex;align-items:center;gap:8px;background:#2c2d30;border-bottom:1px solid #17181a;flex-wrap:wrap}#mm-responsive-cover .rc-options strong{font-size:12px}#mm-responsive-cover #rc-overrides{font-size:11px;color:var(--rc-muted);margin-right:auto}#mm-responsive-cover .rc-canvas-wrap{min-height:200px;flex:1;display:flex;align-items:center;justify-content:center;overflow:hidden;padding:30px;background-color:#222326;background-image:linear-gradient(#ffffff03 1px,transparent 1px),linear-gradient(90deg,#ffffff03 1px,transparent 1px);background-size:24px 24px}#mm-responsive-cover #rc-canvas{max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain;touch-action:none;box-shadow:0 12px 40px #0006;cursor:move}
#mm-responsive-cover .rc-variants{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px;padding:12px 16px;background:#2c2d30;border-top:1px solid #17181a}#mm-responsive-cover .rc-variant{min-width:0;padding:6px;font-size:11px;background:#303135}#mm-responsive-cover .rc-variant[aria-pressed=true]{border-color:#80b5ff;box-shadow:inset 0 0 0 1px #80b5ff;background:#3b4558}#mm-responsive-cover .rc-variant canvas{width:100%;height:68px;object-fit:contain;display:block;margin-bottom:5px}#mm-responsive-cover .rc-variant small{font-size:10px;color:var(--rc-muted);display:block}#mm-responsive-cover .rc-status{font-size:11px;margin:0;padding:6px 16px;color:var(--rc-muted)}#mm-responsive-cover #rc-warning:empty{display:none}#mm-responsive-cover #rc-warning{color:#ffc394}
#mm-responsive-cover .rc-dock{display:flex;flex-direction:column;min-height:0;overflow:auto;background:#303135;border-left:1px solid #17181a}#mm-responsive-cover .rc-dock h3{font-size:12px;font-weight:650;margin:0;padding:10px 12px;border-bottom:1px solid #17181a;letter-spacing:.05em}#mm-responsive-cover .rc-properties{padding:12px;display:grid;gap:10px;height:340px;flex-shrink:0;overflow-y:auto;align-content:start}#mm-responsive-cover label{display:grid;gap:4px;font-size:11px;color:#ced0d5}#mm-responsive-cover textarea{width:100%;resize:vertical;min-height:50px;font-size:13px;line-height:1.55}#mm-responsive-cover select,#mm-responsive-cover input[type=number]{width:100%;min-width:0}#mm-responsive-cover .rc-row{display:flex;gap:8px;align-items:center}#mm-responsive-cover .rc-row label{flex:1;min-width:0}#mm-responsive-cover input[type=range]{width:100%;min-width:0;padding:0;accent-color:#80b5ff}#mm-responsive-cover input[type=color]{width:100%;padding:2px}#mm-responsive-cover .rc-check{display:flex;align-items:center;gap:6px}#mm-responsive-cover input[type=checkbox]{min-height:0;accent-color:#80b5ff}#mm-responsive-cover .rc-hint{font-size:10px;line-height:1.6;color:var(--rc-muted);margin:0}#mm-responsive-cover details{border-top:1px solid var(--rc-line);padding-top:8px}#mm-responsive-cover details summary{cursor:pointer;font-size:12px}#mm-responsive-cover details>div{padding-top:9px;display:grid;gap:9px}
#mm-responsive-cover .rc-layer-section{border-top:1px solid #17181a;flex:1;min-height:260px}#mm-responsive-cover .rc-layer-tools{display:flex;gap:6px;align-items:center;padding:9px 10px;border-bottom:1px solid var(--rc-line)}#mm-responsive-cover .rc-layer-tools label{flex:1;display:flex;align-items:center;gap:6px}#mm-responsive-cover #rc-opacity{width:57px}#mm-responsive-cover .rc-icon{padding:5px;width:30px;min-height:30px;display:inline-flex;align-items:center;justify-content:center}
#mm-responsive-cover .rc-layer-row{display:grid;grid-template-columns:30px 38px minmax(0,1fr) 28px;align-items:center;gap:5px;min-height:48px;padding:4px 7px;border-bottom:1px solid #252629;border-left:2px solid transparent;position:relative;cursor:default;touch-action:none;user-select:none}#mm-responsive-cover .rc-layer-row[aria-selected=true]{background:#414d63;border-left-color:#80b5ff}#mm-responsive-cover .rc-layer-row[data-muted=true] .rc-layer-name{color:#a1a4ac}#mm-responsive-cover .rc-layer-row[data-drop=before]:before,#mm-responsive-cover .rc-layer-row[data-drop=after]:after{content:'';height:2px;background:#92c1ff;position:absolute;left:0;right:0;z-index:1}#mm-responsive-cover .rc-layer-row[data-drop=before]:before{top:0}#mm-responsive-cover .rc-layer-row[data-drop=after]:after{bottom:0}#mm-responsive-cover .rc-layer-row button{border:0;background:none}#mm-responsive-cover .rc-layer-row button:hover{background:#ffffff12}#mm-responsive-cover .rc-thumb{height:32px;width:38px;border:1px solid #666b73;background:#eee;color:#202124;display:flex;align-items:center;justify-content:center;overflow:hidden;font:23px Georgia,serif}#mm-responsive-cover .rc-thumb img{max-width:100%;max-height:100%;object-fit:contain}#mm-responsive-cover .rc-layer-name{display:block;text-align:left;width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:0!important;font-size:12px!important}#mm-responsive-cover .rc-layer-label small{font-size:10px;color:#b6bac4}#mm-responsive-cover .rc-rename{width:100%;min-width:0;font-size:12px;background:#202124}#mm-responsive-cover .rc-pinned{opacity:.72;border-left-color:transparent!important}#mm-responsive-cover .rc-layer-footer{padding:8px 10px;display:flex;align-items:center;gap:6px}#mm-responsive-cover #rc-selection-count{font-size:10px;margin-right:auto;color:var(--rc-muted)}
#mm-responsive-cover .rc-menu{position:fixed;z-index:20;background:#383a3e;border:1px solid #666;border-radius:6px;box-shadow:0 8px 24px #0006;padding:4px;min-width:180px}#mm-responsive-cover .rc-menu button{display:block;width:100%;text-align:left;border:0;background:none}
#mm-responsive-cover footer{padding:10px 16px;display:flex;align-items:center;gap:8px;background:#303135;border-top:1px solid #17181a;flex-shrink:0;flex-wrap:wrap}#mm-responsive-cover footer label{display:flex;align-items:center;gap:8px}#mm-responsive-cover footer input{max-width:190px;font-size:11px}#mm-responsive-cover footer .rc-primary{background:#e6e8ed;color:#202124;border-color:#e6e8ed;font-weight:600}#mm-responsive-cover footer .rc-primary:hover:not(:disabled){background:#fff;color:#151619}
@media(max-width:800px){#mm-responsive-cover{height:98dvh;max-height:98dvh;border-radius:8px}#mm-responsive-cover .rc-body{display:flex;flex-direction:column;overflow:auto}#mm-responsive-cover .rc-rail{display:none}#mm-responsive-cover .rc-stage{flex-shrink:0;overflow:visible}#mm-responsive-cover .rc-canvas-wrap{height:290px;flex:none;padding:16px}#mm-responsive-cover .rc-dock{overflow:visible;display:flex;border-left:0}#mm-responsive-cover .rc-properties{grid-template-columns:1fr 1fr;height:340px}#mm-responsive-cover .rc-properties>details,#mm-responsive-cover .rc-properties>.rc-hint,#mm-responsive-cover .rc-properties>#rc-transform{grid-column:1/-1}#mm-responsive-cover .rc-layer-section{min-height:0}#mm-responsive-cover .rc-variants{grid-template-columns:repeat(3,minmax(0,1fr))}#mm-responsive-cover .rc-variant canvas{height:46px}#mm-responsive-cover header{padding:8px 12px;height:auto;min-height:50px}#mm-responsive-cover header span{display:none}#mm-responsive-cover button,#mm-responsive-cover input,#mm-responsive-cover select{min-height:40px}#mm-responsive-cover .rc-layer-row{min-height:52px}#mm-responsive-cover .rc-icon{width:38px}#mm-responsive-cover .rc-layer-row{grid-template-columns:38px 38px minmax(0,1fr) 38px}#mm-responsive-cover footer{padding:8px}#mm-responsive-cover footer label{display:none}}
</style>
<header><h2 id="mm-responsive-title">一稿 · 多比例</h2><span>MagMark Cover Studio</span><button type="button" id="rc-back">返回自由排版</button><button type="button" id="rc-close" aria-label="关闭多比例封面">关闭</button></header>
<div class="rc-body">
<nav class="rc-rail" aria-label="画布工具"><button id="rc-tool-move" title="移动 / 选择图层 (V)" aria-label="移动 / 选择图层" aria-pressed="true">${icon('move')}</button><button id="rc-tool-text" title="编辑选中文字 (T)" aria-label="编辑选中文字">${icon('text')}</button><button id="rc-tool-image" title="导入 / 替换主图" aria-label="导入 / 替换主图">${icon('image')}</button><hr><button id="rc-tool-guides" title="显示裁切参考线" aria-label="显示裁切参考线" aria-pressed="false">${icon('guides')}</button></nav>
<section class="rc-stage" aria-label="多比例实时预览"><div class="rc-options"><strong id="rc-current"></strong><span id="rc-overrides"></span><button id="rc-undo" type="button">撤销</button><button id="rc-redo" type="button">重做</button></div><div class="rc-canvas-wrap"><canvas id="rc-canvas" tabindex="0" role="img" aria-label="封面画布，点选或拖动图层，方向键微调"></canvas></div><div class="rc-variants" id="rc-variants"></div><p class="rc-status" id="rc-warning" role="status" aria-live="polite"></p><p class="rc-status" id="rc-status" role="status" aria-live="polite">设计保留在当前页面；离开前请保存设计文件。</p></section>
<aside class="rc-dock" aria-label="属性与图层"><h3>属性 <span id="rc-property-name"></span></h3><section class="rc-properties" aria-label="主设计与局部调整">
<label>修改范围<select id="rc-scope"><option value="all">主设计 · 联动全部比例</option><option value="one">仅当前比例 · 局部覆盖</option></select></label><p class="rc-hint">属性按修改范围同步；位置始终仅调整当前画幅。</p>
<label id="rc-title-field">标题<textarea id="rc-title" maxlength="4000"></textarea></label><label id="rc-subtitle-field">副标题<textarea id="rc-subtitle" maxlength="4000"></textarea></label>
<div class="rc-row" id="rc-text-options"><label>字体<select id="rc-font"><option value="serif">编辑宋体</option><option value="sans">现代黑体</option></select></label><label>对齐<select id="rc-align"><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label></div>
<div id="rc-transform"><div class="rc-row"><label>X %<input id="rc-x" type="number" min="0" max="100" step="1"></label><label>Y %<input id="rc-y" type="number" min="0" max="100" step="1"></label><label>宽 %<input id="rc-w" type="number" min="8" max="100" step="1"></label></div><label id="rc-scale-field">字号倍率<input id="rc-scale" type="range" min="40" max="200" value="100"></label></div>
<label hidden>图层<select id="rc-layer"><option value="title">标题</option><option value="subtitle">副标题</option><option value="logo">Logo</option><option value="image">主图</option></select></label><label class="rc-check" hidden><input type="checkbox" id="rc-hidden">隐藏此图层</label>
<details id="rc-image-settings"><summary>主图与裁切焦点</summary><div><label>上传主图<input type="file" id="rc-image" accept="image/png,image/jpeg,image/webp"></label><button type="button" id="rc-clear-image">移除主图</button><label>焦点横向 %<input id="rc-focal-x" type="range" min="0" max="100"></label><label>焦点纵向 %<input id="rc-focal-y" type="range" min="0" max="100"></label><p class="rc-hint">按指定焦点裁切，不拉伸；尚不自动检测人脸。</p></div></details>
<details><summary>文档 · 纸底与安全区</summary><div><div class="rc-row"><label>纸色<input type="color" id="rc-paper"></label><label>字色<input type="color" id="rc-ink"></label></div><label class="rc-check"><input type="checkbox" id="rc-logo">启用 MagMark Logo</label><label class="rc-check"><input type="checkbox" id="rc-safe">关键内容收进居中 1:1 安全区</label><label class="rc-check"><input type="checkbox" id="rc-guides">显示裁切参考线（不导出）</label><button type="button" id="rc-reset">当前比例恢复跟随主设计</button></div></details>
</section><section class="rc-layer-section" id="rc-layer-panel" aria-label="图层管理"></section></aside></div>
<footer><button id="rc-png" class="rc-primary" type="button">当前 PNG</button><button id="rc-zip" type="button">全部 6 比例 ZIP</button><button id="rc-insert" type="button">插入当前 PNG</button><button id="rc-save" type="button">保存可编辑设计</button><label>打开设计<input id="rc-load" type="file" accept="application/json,.json"></label></footer>`;
